name = "digpi-worker"
type = "webpack"

account_id = ""
workers_dev = true
route = "https://digpi.com/dailyjournal/*"
zone_id = ""
compatibility_date = "2021-10-31"

kv_namespaces = [ 
  { binding = "TG_NOTION_MAP", id = "" }
]

# Send a reminder telegram message every night at 8PM
[triggers]
crons = ["0 20 * * *"]

# Telegram Bot Details and Notion Integration Credentials
[vars]
TG_BOT_NAME = ""
TG_BOT_TOKEN = ""
NOTION_API_BASE_URL = "https://api.notion.com/v1"
NOTION_CLIENT_ID = ""
NOTION_CLIENT_SECRET = ""
NOTION_PARENT_PAGE_TITLE = "DigPi"